//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace data_connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoronaDetails
    {
        public Nullable<System.DateTime> Vaccine1Date { get; set; }
        public Nullable<System.DateTime> Vaccine2Date { get; set; }
        public Nullable<System.DateTime> Vaccine3Date { get; set; }
        public Nullable<System.DateTime> Vaccine4Date { get; set; }
        public string Vaccine1Manufacturer { get; set; }
        public string Vaccine2Manufacturer { get; set; }
        public string Vaccine3Manufacturer { get; set; }
        public string Vaccine4Manufacturer { get; set; }
        public Nullable<System.DateTime> PositiveResultDate { get; set; }
        public Nullable<System.DateTime> RecoveryDate { get; set; }
        public string ID { get; set; }
    }
}
