//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace data_connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERES_HMO
    {
        public string First_name { get; set; }
        public string Last_name { get; set; }
        public System.DateTime Birth_date { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public int building_number { get; set; }
        public string cellphone { get; set; }
        public string phone { get; set; }
        public string ID { get; set; }
    }
}
